# Site settings
title: Inspiredown
email: justin@jplt.com
description: > # this means to ignore newlines until "baseurl:"
  Simple inspirational countdown timers.  You bring a picture and
  a time and we'll do the rest.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.inspiredown.com" # the base hostname & protocol for your site
twitter_username: potatono
github_username:  potatono

# Build settings
markdown: kramdown
